# Generated by Django 5.1 on 2024-10-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PuntoVerde',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('materiales', models.TextField()),
                ('mas_info', models.TextField()),
                ('dia_hora', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('cooperativa', models.CharField(max_length=255)),
                ('calle', models.CharField(max_length=100)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('calle2', models.CharField(blank=True, max_length=100)),
                ('barrio', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=20)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
    ]
