# Generated by Django 5.1 on 2024-10-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsejosRRR',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('reciclaje', 'Reciclaje'), ('reutilizacion', 'Reutilización'), ('reduccion', 'Reducción de Consumo')], default='reciclaje', max_length=20)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Consejo RRR',
                'verbose_name_plural': 'Consejos RRR',
            },
        ),
    ]
