# Generated by Django 5.1 on 2024-10-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_consejosrrr'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioAmbiental',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
