# Generated by Django 5.2.8 on 2025-11-29 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_calendarioambiental'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsejosRRR',
            new_name='Consejo',
        ),
        migrations.AlterModelOptions(
            name='consejo',
            options={'verbose_name': 'Consejo', 'verbose_name_plural': 'Consejos'},
        ),
    ]
