# Generated by Django 4.2 on 2025-12-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_chatsession_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consejo',
        ),
    ]
