# Generated by Django 5.2.9 on 2025-12-16 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_eventousuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoverde',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puntoverde',
            name='is_user_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PuntoVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('valid', 'Validar'), ('invalid', 'Invalidar')], max_length=10)),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='myapp.puntoverde')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'punto')},
            },
        ),
    ]
