# Generated by Django 5.2.9 on 2025-12-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_puntoverde_creator_puntoverde_is_user_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoverde',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='puntoverde',
            name='calle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='puntoverde',
            name='comuna',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='puntoverde',
            name='dia_hora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='puntoverde',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='puntoverde',
            name='mas_info',
            field=models.TextField(blank=True, default='Creado por la comunidad', null=True),
        ),
    ]
