# Generated by Django 5.2.12 on 2026-03-31 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_puntoverde_barrio_alter_puntoverde_calle_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE auth_user ADD CONSTRAINT unique_email UNIQUE (email);"
        ),
    ]
